---
spring:
  application:
    name: sample-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations: classpath:/config

server:
  port: 8888

eureka:
  instance:
    nonSecurePort: ${server.port:8888}
  client:
    serviceUrl:
      defaultZone: http://${eureka.host:localhost}:${eureka.port:8761}/eureka/

